version: 2

services:
 influxdb:
  image: influxdb:latest
  ports:
     - "8086:8086"
  restart: always 
 grafana:
  image: grafana/grafana:latest
  ports:
     - "3000:3000"
  volumes:
     - "/host_mnt/d/docker/grafana:/var/lib/grafana/"
  restart: always 
 loki:
  image: grafana/loki:latest
  ports:
     - "3100:3100"
 registry:
  image: registry:2
  ports:
     - "5000:5000"
  volumes:
     - "/mnt/d/docker/registry:/var/lib/registry/"
  restart: always
 splunk:
  image:  splunk/splunk:latest
  ports:
     - "8001:8000"
     - "8089:8089"
  environment:
   - SPLUNK_START_ARGS= "--accept-license"
   - SPLUNK_PASSWORD= "<password>"
  volumes:
    - splunk:"/opt/splunk/var"
    - splunk-etc:"/opt/splunk/etc"
  restart: always 
    
