version: 2
services:
 gitlab:
  image:   gitlab/gitlab-ce:latest
  ports:
     - "80:80"
     - "22:22"
     - "443:443"
  volumes:
    - gitlab-etc:/etc/gitlab
    - gitlab-log:/var/log/gitlab
    - gitlab-data:/var/opt/gitlab 
  restart: always 
  
  
