version: 2
services:
 gitlab:
  image:    gitlab/gitlab-ce:latest
  ports:
     - "80:80"
     - "22:22"
     - "443:443"
  environment:
   - SPLUNK_START_ARGS= "--accept-license"
   - SPLUNK_PASSWORD= "<password>"
  volumes:
    - "/mnt/d/gitlab/etc:/etc/gitlab"
    - "/mnt/d/gitlab/log:/var/log/gitlab"
    - "/mnt/d/gitlab/data:/var/opt/gitlab" 
  restart: always 
  
  
