version: 2

services:
 splunk:
  image:  splunk/splunk:latest
  ports:
     - "8000:8001"
     - "8089:8089"
  environment:
   - SPLUNK_START_ARGS= "--accept-license"
   - SPLUNK_PASSWORD= "<password>"
  volumes:
   - "/mnt/d/docker/splunk:/opt/splunk/var"
  restart: always 
